
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 20 19:02:50 ART 2017
//----------------------------------------------------

package lang.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int AND = 3;
  public static final int P1 = 7;
  public static final int id = 13;
  public static final int EOL = 9;
  public static final int valor = 12;
  public static final int BICOND = 6;
  public static final int num = 14;
  public static final int EQ = 10;
  public static final int EOF = 0;
  public static final int COND = 5;
  public static final int COMMA = 11;
  public static final int error = 1;
  public static final int NOT = 2;
  public static final int OR = 4;
  public static final int P2 = 8;
}

