
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 04 18:21:24 UYT 2017
//----------------------------------------------------

package lang.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int P1 = 2;
  public static final int id = 14;
  public static final int COLON = 4;
  public static final int bool = 16;
  public static final int UNION = 7;
  public static final int INTERSECTION = 6;
  public static final int ELEMENTS = 12;
  public static final int num = 13;
  public static final int EOF = 0;
  public static final int ATTRIBUTES = 11;
  public static final int CONCATENATION = 8;
  public static final int str = 15;
  public static final int DIFFERENCE = 9;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int FILTER = 10;
  public static final int P2 = 3;
}

