
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 30 17:06:22 UYT 2017
//----------------------------------------------------

package lang.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int NUM = 4;
  public static final int COMMA = 3;
  public static final int EOL = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

