
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 05 07:34:12 UYT 2017
//----------------------------------------------------

package lang.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int DIFERENCIA = 10;
  public static final int CONCATENACION = 9;
  public static final int P2 = 3;
  public static final int P1 = 2;
  public static final int INTERSECCION = 7;
  public static final int num = 14;
  public static final int COLON = 4;
  public static final int EOL = 6;
  public static final int bool = 17;
  public static final int ATTRIBUTES = 12;
  public static final int COMMA = 5;
  public static final int EOF = 0;
  public static final int ELEMENTS = 13;
  public static final int id = 15;
  public static final int str = 16;
  public static final int UNION = 8;
  public static final int error = 1;
  public static final int fil = 18;
  public static final int FILTRO = 11;
}

